allapps/dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('history/', views.history, name='history'),
]

weatherdashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('allapps.dashboard.urls', namespace='dashboard')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

allapps/dashboard/models.py
from django.db import models


# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'cities'

    def __str__(self):
        return self.name

allapps/dashboard/forms.py
from django import forms
from django.forms import widgets
from .models import City


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control my-3',
                'placeholder': 'Enter City Name...'
            })
        }
        labels = {
            'name': '',
        }

allapps/dashboard/views.py
from django.shortcuts import render, redirect
from .forms import CityForm
from .models import City
from django.conf import settings
import requests
from time import timezone


# Create your views here.
def get_weather_data(city_name):
    url = 'https://api.openweathermap.org/data/2.5/weather/'

    params = {
        'q': city_name,
        'appid': settings.OWM_API_KEY,
        'units': 'metric',
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        return

    json_response = response.json()

    weather_data = {
        'temp': json_response['main']['temp'],
        'temp_min': json_response['main']['temp_min'],
        'temp_max': json_response['main']['temp_max'],
        'city_name': json_response['name'],
        'country': json_response['sys']['country'],
        'lat': json_response['coord']['lat'],
        'lon': json_response['coord']['lon'],
        'weather': json_response['weather'][0]['main'],
        'weather_desc': json_response['weather'][0]['description'],
        'pressure': json_response['main']['pressure'],
        'humidity': json_response['main']['humidity'],
        'wind_speed': json_response['wind']['speed'],
    }

    return weather_data


def index(request):
    weather_data = request.session.get('weather_data', False)
    if weather_data:
        del request.session['weather_data']

    form = CityForm(request.POST or None)

    if not weather_data and request.method == 'GET':
        try:
            name = City.objects.latest('updated_at').name
            weather_data = get_weather_data(name)
        except Exception as e:
            weather_data = get_weather_data('Pune')

    if form.is_valid():
        form.save(commit=False)
        name = form.cleaned_data['name'].capitalize()
        weather_data = get_weather_data(name)
        request.session['weather_data'] = weather_data
        if weather_data:
            try:
                city = City.objects.get(name=name)
                city.name = name
                city.save()
            except Exception as e:
                City.objects.create(name=name)
        return redirect('dashboard:index')
    return render(request, 'dashboard/index.html', {'form': form, 'weather_data': weather_data})


def history(request):
    cities = City.objects.all().order_by('-updated_at')[:5]

    weather_data_list = []
    for city in cities:
        weather_data_list.append(get_weather_data(city.name))

    return render(request, 'dashboard/history.html', {'weather_data_list': weather_data_list})

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %}</title>

	<!-- MDB -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/2.2.1/mdb.min.css" rel="stylesheet" />

	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
	{% include '_navbar.html' %}

	{% block content %}
	{% endblock %}

	{% include '_footer.html' %}

	<!-- MDB -->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/2.2.1/mdb.min.js"></script>
</body>

</html>

templates/_card.html
<div class="container">
	<div class="card my-2">
		<div class="card-header border-0">
			<h5 class="card-title pb-3">Weather Information</h5>
			<div class="d-flex justify-content-center align-items-center">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<h1 class="card-title">{{ weather_data.temp }}&deg;</h1>
							<p class="card-text pt-2">
								{{ weather_data.temp_min }}&deg;C - {{ weather_data.temp_max }}&deg;C
							</p>
						</div>
						<div class="col-md-6">
							<p>{{ weather_data.city_name }}<small>({{ weather_data.country }})</small></p>
							<div><small class="text-muted">Longitude: {{ weather_data.lon }}</small></div>
							<div><small class="text-muted">Latitude: {{ weather_data.lat }}</small></div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="card-body">
			<ul class="list-group list-group-flush py-3">
				<li class="list-group-item">
					<strong>Weather: </strong>
					<span>
						{{ weather_data.weather }}({{ weather_data.weather_desc }})
					</span>
				</li>
				<li class="list-group-item"><strong>Pressure: </strong><span>{{ weather_data.pressure }}</span></li>
				<li class="list-group-item"><strong>Humidity: </strong><span>{{ weather_data.humidity }}</span></li>
				<li class="list-group-item"><strong>Wind Speed: </strong><span>{{ weather_data.wind_speed }}</span></li>
			</ul>
		</div>
	</div>
</div>

templates/_footer.html
<footer class="bg-dark py-2 text-center">
	&copy; 2020 Copyright, CodeDjango
</footer>

templates/_navbar.html
<header>
	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed">
		<!-- Container wrapper -->
		<div class="container-fluid">
			<!-- Navbar brand -->
			<a class="navbar-brand" href="{% url 'dashboard:index' %}">WeatherDashBoard</a>

			<!-- Toggle button -->
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<i class="fas fa-bars"></i>
			</button>

			<!-- Collapsible wrapper -->
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<!-- Left links -->
				<!--
					<ul class="navbar-nav mr-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="#">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Link</a>
						</li>
					</ul>
				-->
				<!-- Left links -->

				<!-- Search form -->
				<form class="d-flex input-group w-auto ml-auto">
					<input type="search" class="form-control" placeholder="Type query" aria-label="Search" />
					<button class="btn btn-outline-primary" type="button" data-ripple-color="dark">
						Search
					</button>
				</form>
			</div>
			<!-- Collapsible wrapper -->
		</div>
		<!-- Container wrapper -->
	</nav>
	<!-- Navbar -->
</header>

templates/_sidebar.html
<div class="container">
	<p class="lead">What's the weather like?</p>
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-warning">Search</button>
		<a class="btn btn-warning ml-2" type="button" href="{% url 'dashboard:history' %}">History</a>
	</form>
</div>

templates/dashboard/history.html
{% extends '_base.html' %}
{% load static %}


{% block title %}
Weather | History
{% endblock %}


{% block content %}
<div class="container">
	<div class="row">
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">Home</a></li>
				<li class="breadcrumb-item active" aria-current="page">History</li>
			</ol>
		</nav>
		{% for weather_data in weather_data_list %}
		<div class="container">
			<div class="row">
				<div class="col-md-6 offset-md-3">
					{% include '_card.html' %}
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/dashboard/index.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
Dashboard | Home
{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4 d-flex justify-content-center align-items-center text-center" id="sidebar">
			<!-- Side Bar -->
			{% include '_sidebar.html' %}
		</div>
		<div class="col-md-8 d-flex justify-content-center align-items-center text-center">
			<!-- Card -->
			<main>
				{% include '_card.html' %}
			</main>
		</div>
	</div>
</div>
{% endblock %}